### ISSUE TITLE
mac 10.3 make failed

### ISSUE THREAD

**Issue by logofox** [TrueFurby/go-callvis#11]
# cd github.com/TrueFurby/go-callvis/ && make
go get github.com/golang/dep/cmd/dep
dep ensure -update
make: dep: No such file or directory
make: *** [dep] Error 1

**Comment by TrueFurby** [comment]
No way for me to test this. But I checked the Makefile and the only reason I found it might be is the order of targets.

I have changed the order, try updating the repository and trying again.

**Comment by TrueFurby** [comment]
Okay. I tried doing clean install and found out the problem was due some recent changes in dep tool. Using Godep.* files instead manifest/lock.json. I committed https://github.com/TrueFurby/go-callvis/commit/a5f9bf85971e9874d9aa4f376cb03942b3a92939 to fix this. Try with the latest changes.

**Comment by yilin0830** [comment]
cd go-callvis/ && make
-------------------------
go get -u github.com/golang/dep/cmd/dep
dep ensure -update
make: dep: No such file or directory
make: *** [dep] Error 1

**Comment by TrueFurby** [comment]
Did you run:

```
go get -u github.com/TrueFurby/go-callvis
cd $GOPATH/src/github.com/TrueFurby/go-callvis && make
```

I just tested clean install and everything works for me. However I have no way to test this on mac.

**Comment by mixeract** [comment]
Still issues on macOS 10.12
```
$ go get -u github.com/TrueFurby/go-callvis
$ cd $GOPATH/src/github.com/TrueFurby/go-callvis && make
go get -u github.com/golang/dep/cmd/dep
dep ensure -update
make: dep: No such file or directory
make: *** [dep] Error 1
```

**Comment by garrettr** [comment]
I have the same issue on macOS 10.12.6. It is due to the lack of `$GOPATH/bin` in `$PATH`. The Makefile assumes that it is included when it tries to call `dep` after installing it.

I think it would be better to prefix all calls to dependencies installed with `go get` with `$GOPATH/bin` in the Makefile, since that will work regardless of whether you have added `$GOPATH/bin` to your `$PATH`. While that may be a popular modification among Gophers, it is not set by the default installer (which only adds `$GOROOT` to your `$PATH`), is not mentioned in the official [install docs](https://golang.org/doc/install), and is only suggested as an optional modification for convenience in ["How to write Go code"](https://golang.org/doc/code.html).
